# Generated by Django 4.0.5 on 2022-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter_accept_village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_id', models.BigIntegerField()),
                ('accept_village', models.CharField(max_length=255)),
            ],
        ),
    ]
